// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThumbsComments.Models;

namespace ThumbsComments.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190121134928_inital")]
    partial class inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThumbsComments.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LineOfBusiness")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("ThumbComment");

                    b.HasKey("Id");

                    b.HasIndex("LineOfBusiness")
                        .IsUnique();

                    b.ToTable("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
